### ISSUE TITLE
Tips on connecting to scriptcraft files on Azure?

### ISSUE THREAD

**Issue by michaelprosario** [tclavier/docker-scriptcraft#4]
Hi.

Let me start off by saying that I appreciate the work you've done to create this scriptcraft server on docker.  The setup was really easy so far.   For background, I've started to invoke the the system by doing the following:

sudo docker run -p 25565:25565 -p 23:22 -it tclavier/scriptcraft

I'm running Ubuntu 14 on Azure.  

I have port 8080 forwarding to port 23. 

Do you have any other tips on how I can connect to the scriptcraft server to upload files using sftp?

I do appreciate it!

**Comment by tclavier** [comment]
You forward port 8080 to 23 and 23 to 22 ... so complicated ... have you test to point your sftp client to your host on port 8080 ?

**Comment by michaelprosario** [comment]
Unfortunately. It does not work.
