### ISSUE TITLE
Upgrade to MC 1.12.1?

### ISSUE THREAD

**Issue by TonyGravagno** [tclavier/docker-scriptcraft#6]
If you're interested in updating this docker image, I'm working on a [new build](https://github.com/TonyGravagno/ScriptCraft) of ScriptCraft. It would be great if we could announce a beta version in a container so that people don't face possible corruption of their live environments. Another update will be necessary when ScriptCraft gets an official update. Thanks.

**Comment by tclavier** [comment]
Done with commit : 7baeb0b0f1629ee987e7cfda616bfa8f9933b092
