### ISSUE TITLE
Can't interact with console

### ISSUE THREAD

**Issue by gubraun** [tclavier/docker-scriptcraft#9]
Great work on putting together the container! 

Issue: I can't interact with the console. I see the output, but it seems stdin not appreciated. I ran the container as:

docker run -p 25565:25565 -it --rm -v minecraft:/minecraft tclavier/scriptcraft

using Docker Toolbox on a Windows 10 machine.

**Comment by tclavier** [comment]
What do you want to do ? the [start command](https://github.com/tclavier/docker-scriptcraft/blob/52a4065cf6bd71dd019a9d19e5d30d3381ff787c/start#L14) take the stdin of java command to send "jsp classroom on". After that, it's not possible to send other command. You can send CTRL+C signal to stop bukkit.

**Comment by gubraun** [comment]
Sorry, didn't figure that you pipe from stdin. I wanted to keep the server react to commands through stdin. I could easily achieve that by changing the line in the start script.
